### ISSUE TITLE
Website Loading

### ISSUE THREAD

**Issue by Tanoswolf** [ChristopherLlewellyn/tarkov-lens-app#1]
Hello, 
I would love to use your website, but if I try to use the pen calculator the website seems to load infinite and doesnt let me select an amor. I hope you could may help. 

Thank you in advanced

**Comment by ChristopherLlewellyn** [comment]
@Tanoswolf Hey, thanks for the message.

I stopped maintaining the project last year. The website is no longer working, and even if it was, it would be out of date due to changes in the game. Sorry about that.

If you wish to use a similar application, check out "Battlebuddy" on Android and iOS.

**Comment by Tanoswolf** [comment]
Thank you very much for the quick response and the clarification, aswell as the link to other services.
